/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jetbrains.swingapp;

import javax.swing.*;
import java.awt.*;

public class App extends JFrame {

     // default dimensions 
    private int width = 1024,
                height = 720;

    // constructor
    public App() {
        super("SQLite Viewer");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(width, height);
        setResizable(false);
        setLocationRelativeTo(null);
        setLayout(null);
        setLayout(new BoxLayout(getContentPane(), BoxLayout.Y_AXIS));

        initOpenFile();
        // seperator
        add(Box.createRigidArea(new Dimension(10, 0)));
        // seperator
        initSQLArea();

        setVisible(true);
    }


    private void initSQLArea() {
        JPanel Panel_SQLArea = new JPanel();
        Panel_SQLArea.setName("Panel_SQLArea");
        Panel_SQLArea.setSize(800, 200);
        Panel_SQLArea.setBackground(Color.RED);
        //Panel_SQLArea.setLayout(new BoxLayout(Panel_SQLArea, BoxLayout.X_AXIS));
        Panel_SQLArea.setLayout(new FlowLayout());
        add(Panel_SQLArea);
        
        JTextArea textBox = new JTextArea("SELECT *FROM contacts;");
        textBox.setName("QueryTextArea");
        textBox.setSize(800, 200);
        Dimension d = textBox.getPreferredSize();
        textBox.setMinimumSize(new Dimension(1000, d.height + 60));
        textBox.setMaximumSize(new Dimension(1000, d.height + 60));
        Panel_SQLArea.add(textBox);

        JButton executeButton = new JButton("Execute");
        executeButton.setName("ExecuteQueryButton");
        executeButton.setBounds(
                Panel_SQLArea.getWidth(),
                Panel_SQLArea.getY(),
                100,
                30
            );
        // seperator
        Panel_SQLArea.add(Box.createRigidArea(new Dimension(10, 0)));
        // seperator
        Panel_SQLArea.add(executeButton);
    }


    private void initOpenFile() {
        JPanel Panel_OpenFile = new JPanel();
        Panel_OpenFile.setName("Panel_FileName");
        Panel_OpenFile.setBounds(
                10, 10, getWidth() -40, 30
                );
        Panel_OpenFile.setBackground(Color.YELLOW);
        Panel_OpenFile.setLayout(new BoxLayout(Panel_OpenFile, BoxLayout.X_AXIS));
        add(Panel_OpenFile);

        JTextField fileField = new JTextField();
        fileField.setName("FileNameTextField");
        Dimension d = fileField.getPreferredSize();
        fileField.setMaximumSize(new Dimension(1000, d.height + 6));
        fileField.setHorizontalAlignment(JTextField.LEADING);
        Panel_OpenFile.add(fileField);

        // seperator
        Panel_OpenFile.add(Box.createRigidArea(new Dimension(10, 0)));

        JButton openButton = new JButton("Open");
        openButton.setName("OpenFileButton");
        openButton.setBounds(
                Panel_OpenFile.getWidth(),
                Panel_OpenFile.getY(),
                100,
                30
            );
        Panel_OpenFile.add(openButton);
    }


    // init Flow Layout
    private void initAppFlow() {
        int boxTail = 200;

        JTextField field_FileName_01 = new JTextField();
        field_FileName_01.setName("FileNameTextField");
        field_FileName_01.setBounds(10, 20, getWidth() -boxTail, 30);
        add(field_FileName_01);

        JButton openButton = new JButton("Open");
        openButton.setName("OpenFileButton");
        openButton.setBounds(getWidth() -boxTail +20, 20, 100, 30);
        add(openButton);

        setLayout(new FlowLayout(FlowLayout.CENTER, 20, 10));
    }

    public static void main(final String[] args) {
        new App();
    }
}
